### ISSUE TITLE
Rename this repo to akka-quickstart-java

### ISSUE THREAD

**Issue by ktoso** [akka/akka-quickstart-java.g8#12]
And make sure to check if all docs are using the new name

**Comment by ktoso** [comment]
Confirmed all links on http://developer.lightbend.com/start/?group=akka and downloads still work, same with our akka.io site, which only linked to developer lightbend

**Comment by patriknw** [comment]
Did you change in example code service (I'm not sure how it works)?
cc @henrikengstrom

**Comment by ktoso** [comment]
I'm not sure myself but http://developer.lightbend.com/start/?group=akka seems to work (the download button) the link too http://developer.lightbend.com/guides/akka-quickstart-scala/

**Comment by henrikengstrom** [comment]
I don't know exactly, but it could be now that the Example Code Service does not pick up any changes done in the repo?

Here's the PR that I created for the quickstart projects: https://github.com/typesafehub/example-code-service/pull/99/files
As you can see it refers to `akka-scala-seed.g8` and `akka-java-seed.g8`. So I would guess that this information needs to be updated to reflect the name changes of the repo?

**Comment by patriknw** [comment]
I guess that somewhere the repository is registered so that when push changes those are trickling all the way to the download zip and to the guide. @eed3si9n do you know where we need to update when we rename the github repository?

**Comment by ktoso** [comment]
Oh I see, I submitted a PR where we can continue discussion on that what/when to change there
