### ISSUE TITLE
build.gradle uses mavenLocal repository

### ISSUE THREAD

**Issue by rmcloughlin** [akka/akka-quickstart-java.g8#14]
The `build.gradle` file in this project uses `mavenLocal`:

```
repositories {
    mavenLocal()
}
```

This means that the command `gradle run` will fail if you haven't already downloaded the necessary akka jars into your .m2 cache.  The `build.gradle` file should use `mavenCentral()` instead.

**Comment by ktoso** [comment]
Thanks a lot :) Such things are easy to contribute, you can do so via the online editor even: https://github.com/akka/akka-quickstart-java.g8/edit/2.5.x/src/main/g8/build.gradle
