### ISSUE TITLE
Java documentation talks about using bang method from Scala API

### ISSUE THREAD

**Issue by rmcloughlin** [akka/akka-quickstart-java.g8#16]
Sorry, I'm not sure where to file this bug.  This page: http://developer.lightbend.com/guides/akka-quickstart-java/communicate-with-actors.html says

`use the ! (bang) method on the ActorRef`

But that's how things are done in Scala, not Java.

**Comment by ktoso** [comment]
Thanks! That's the right place to report these.
Seems we missed that one when converting to java - thanks for reporting.
