### ISSUE TITLE
Documentation issue on https://developer.lightbend.com/guides/akka-quickstart-java/

### ISSUE THREAD

**Issue by neildsouza** [akka/akka-quickstart-java.g8#45]
Hi all,
Just wanted to submit a few doc issues based on the Quickstart guide.
1. In the console output for Gradle on that page, the type of the Bot should be `GreeterBot` and not `HelloWorldBot`.

2. Also on the same page, in the **What Hello World does** section, the first bullet point should be `Greeter` and not `Greet`.

Hope this helps.

**Comment by patriknw** [comment]
@neildsouza Thanks for reporting. Would you also be able to create a pull request fixing those issues?
