### ISSUE TITLE
The quickstart example is broken on Gradle 7

### ISSUE THREAD

**Issue by martinandersson** [akka/akka-quickstart-java.g8#61]
Following the instructions on this page:

https://developer.lightbend.com/guides/akka-quickstart-java/

Output of `gradle run` is:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/c/Habib/hello-akka/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'hello-akka'.
> Could not find method compile() for arguments [com.typesafe.akka:akka-actor-typed_2.13:2.6.14] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

Using Gradle 7.0 and Java 11.

Room for improvement:
- Document supported versions of the environment (Gradle, Java)
- Use Gradle wrapper
- Make the build file minimal (remove the `idea` plugin, and more?)

Edit: Found that it does work on Gradle 6.9. So I have a feeling Akka doesn't work at all on Gradle 7?

**Comment by johanandren** [comment]
Looks like the dependency "configurations" currently used has been removed in Gradle 7 (after being deprecated for a while) and we need to update the gradle build file to some other way of defining the dependencies (https://docs.gradle.org/7.0.2/userguide/building_java_projects.html#sec:java_dependency_management_overview).

This is only about the gradle build file in this template and not whether Akka can be used with gradle in general.

**Comment by martinandersson** [comment]
I'm sorry but I don't think I understand. Are you saying the `configurations` block has been removed in Gradle 7? I don't think so. I have it in my own project and it's working just fine. What would be the replacement for their `configurations` block I don't know lol.

**Comment by johanandren** [comment]
Sorry, not familiar with what the right gradle terminology was to describe the change, the project uses a dependency block like this: https://github.com/akka/akka-quickstart-java.g8/blob/2.6.x/src/main/g8/build.gradle#L12

Which apparently isn't allowed anymore with gradle 7 but I'm not entirely sure what the replacement dependency declaration should look like. If you are more knowledgeable a PR with the right kind of dependency block would be highly appreciated.
